//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcurementErp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SOURCING_CATEGORIES> SOURCING_CATEGORIES { get; set; }
        public virtual DbSet<SOURCING_CONTACTEDVENDOR> SOURCING_CONTACTEDVENDOR { get; set; }
        public virtual DbSet<SOURCING_CONTACTPERSON> SOURCING_CONTACTPERSON { get; set; }
        public virtual DbSet<SOURCING_REF_TEMP_LINK> SOURCING_REF_TEMP_LINK { get; set; }
        public virtual DbSet<SOURCING_REQUEST_FILES> SOURCING_REQUEST_FILES { get; set; }
        public virtual DbSet<SOURCING_REQUEST_TYPE> SOURCING_REQUEST_TYPE { get; set; }
        public virtual DbSet<SOURCING_RFQ_QUOTATION> SOURCING_RFQ_QUOTATION { get; set; }
        public virtual DbSet<SOURCING_RFQ_REQ> SOURCING_RFQ_REQ { get; set; }
        public virtual DbSet<SOURCING_ROLES> SOURCING_ROLES { get; set; }
        public virtual DbSet<SOURCING_USERS> SOURCING_USERS { get; set; }
        public virtual DbSet<SOURCING_VENDOR_LOGIN_DETAILS> SOURCING_VENDOR_LOGIN_DETAILS { get; set; }
        public virtual DbSet<SOURCING_MESSAGE> SOURCING_MESSAGE { get; set; }
        public virtual DbSet<SOURCING_MESSAGE_RECIPIENT> SOURCING_MESSAGE_RECIPIENT { get; set; }
        public virtual DbSet<SOURCING_PROPOSAL> SOURCING_PROPOSAL { get; set; }
        public virtual DbSet<SOURCING_REQUEST> SOURCING_REQUEST { get; set; }
        public virtual DbSet<SOURCING_RFP_RFI_REQ> SOURCING_RFP_RFI_REQ { get; set; }
        public virtual DbSet<SOURCING_RFQ_ITEM> SOURCING_RFQ_ITEM { get; set; }
        public virtual DbSet<SOURCING_NEG_PRICE> SOURCING_NEG_PRICE { get; set; }
        public virtual DbSet<SOURCING_NEGOTIATIONS> SOURCING_NEGOTIATIONS { get; set; }
    }
}
