//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcurementErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOURCING_MESSAGE_RECIPIENT
    {
        public decimal ID { get; set; }
        public Nullable<decimal> RECIPIENT_ID { get; set; }
        public Nullable<decimal> RECIPIENT_GROUP_ID { get; set; }
        public string RECIPIENT_TYPE { get; set; }
        public Nullable<decimal> MESSAGE_ID { get; set; }
        public Nullable<decimal> IS_READ { get; set; }
    }
}
