//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcurementErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOURCING_MESSAGE
    {
        public decimal ID { get; set; }
        public Nullable<decimal> TEMP_ID { get; set; }
        public Nullable<decimal> CREATORID { get; set; }
        public string CREATORTYPE { get; set; }
        public string MAIL_SUBJECT { get; set; }
        public Nullable<decimal> PARENT_MESSAGE_ID { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public string MESSAGE_BODY { get; set; }
    }
}
