//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcurementErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOURCING_REQUEST_TYPE
    {
        public decimal REQUEST_ID { get; set; }
        public string REQUEST_NAME { get; set; }
        public string REQUEST_SHORTCODE { get; set; }
    }
}
