//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcurementErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOURCING_RFQ_REQ
    {
        public decimal TEMP_NO { get; set; }
        public Nullable<System.DateTime> RFQ_START_DATE { get; set; }
        public Nullable<System.DateTime> RFQ_CLOSE_DATE { get; set; }
        public Nullable<decimal> INITIATOR_ID { get; set; }
        public string INITIATOR_NAME { get; set; }
        public string DELIVERY_ADDRESS { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> NEGTOTALAMT { get; set; }
        public Nullable<decimal> NEGVAT { get; set; }
        public Nullable<decimal> NEGVATVALUE { get; set; }
        public Nullable<decimal> NEGGRANDTOTAL { get; set; }
        public Nullable<decimal> EXECTOTALAMT { get; set; }
        public Nullable<decimal> EXECVAT { get; set; }
        public Nullable<decimal> EXECVATVALUE { get; set; }
        public Nullable<decimal> EXECGRANDTOTAL { get; set; }
        public Nullable<decimal> MAPPING { get; set; }
    }
}
