//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcurementErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOURCING_RFP_RFI_REQ
    {
        public decimal TEMP_ID { get; set; }
        public string PRJECT_TITLE { get; set; }
        public Nullable<System.DateTime> ISSUE_DATE { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public string DUE_TIME { get; set; }
        public string UBN_OVERVIEW { get; set; }
        public string PROJECT_OBJECTIVE { get; set; }
        public string WORK_SCOPE { get; set; }
        public string TECHNICAL_PROPOSAL { get; set; }
        public Nullable<System.DateTime> LST_QRY_RECEIPT_DATE { get; set; }
        public Nullable<System.DateTime> BANK_QRY_RES_DATE { get; set; }
        public Nullable<System.DateTime> LST_RPF_RECPT_DATE { get; set; }
        public Nullable<decimal> INITIATOR { get; set; }
        public string INITIATOR_NAME { get; set; }
        public Nullable<System.DateTime> INITIATION_DATE { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> NEGTOTALAMT { get; set; }
        public Nullable<decimal> NEGVAT { get; set; }
        public Nullable<decimal> NEGVATVALUE { get; set; }
        public Nullable<decimal> NEGGRANDTOTAL { get; set; }
        public Nullable<decimal> EXECTOTALAMT { get; set; }
        public Nullable<decimal> EXECVAT { get; set; }
        public Nullable<decimal> EXECVATVALUE { get; set; }
        public Nullable<decimal> EXECGRANDTOTAL { get; set; }
        public Nullable<decimal> MAPPING { get; set; }
    }
}
