//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcurementErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOURCING_REQUEST_FILES
    {
        public decimal FIILE_ID { get; set; }
        public Nullable<decimal> SOURCE_REQ_ID { get; set; }
        public string FILENAME { get; set; }
        public string FILETYPE { get; set; }
        public string FILE_PATH { get; set; }
        public Nullable<decimal> VENDORID { get; set; }
    }
}
