//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcurementErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOURCING_REF_TEMP_LINK
    {
        public decimal ID { get; set; }
        public Nullable<decimal> TEMP_NO { get; set; }
        public string REF_NO { get; set; }
        public Nullable<decimal> REQ_TYPE { get; set; }
    }
}
