//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcurementErp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOURCING_NEGOTIATIONS
    {
        public decimal NEG_NO { get; set; }
        public Nullable<decimal> RESPONSE_NO { get; set; }
        public string NEGOTIATOR { get; set; }
        public Nullable<decimal> TEMP_ID { get; set; }
        public Nullable<decimal> VENDOR_ID { get; set; }
        public Nullable<System.DateTime> RES_DATE { get; set; }
        public Nullable<decimal> TOTAL_AMT { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> VATVALUE { get; set; }
        public Nullable<decimal> GRANDTOTAL { get; set; }
        public string STATUS { get; set; }
    }
}
