//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcurementErpVendor
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOURCING_PROPOSAL
    {
        public decimal ID { get; set; }
        public Nullable<decimal> VENDORID { get; set; }
        public Nullable<decimal> TEMPID { get; set; }
        public string PROPOSAL { get; set; }
        public Nullable<decimal> REQUEST_TYPE { get; set; }
    }
}
