//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcurementErpVendor
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOURCING_USERS
    {
        public decimal USER_ID { get; set; }
        public string USERNAME { get; set; }
        public string EMAIL { get; set; }
        public string EMP_NUM { get; set; }
        public string NAME { get; set; }
        public string DESIGNATION { get; set; }
        public string DEPARTMENT { get; set; }
        public string TELEPHONE { get; set; }
        public string CATEGORY { get; set; }
        public string ROLE { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> CATEGORY_ID { get; set; }
        public Nullable<decimal> ROLE_ID { get; set; }
    
        public virtual SOURCING_CATEGORIES SOURCING_CATEGORIES { get; set; }
        public virtual SOURCING_ROLES SOURCING_ROLES { get; set; }
    }
}
