//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcurementErpVendor
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOURCING_CONTACTPERSON
    {
        public decimal ID { get; set; }
        public Nullable<decimal> TEMP_NO { get; set; }
        public string NAME { get; set; }
        public string DESIGNATION { get; set; }
        public string DEPARTMENT { get; set; }
        public string TELEPHONE { get; set; }
        public string CONTACT_TYPE { get; set; }
        public string EMAIL { get; set; }
    }
}
