//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcurementErpVendor
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOURCING_REQUEST
    {
        public decimal TEMP_ID { get; set; }
        public string ITEM_CATEGORY { get; set; }
        public string INITIATOR_NAME { get; set; }
        public string INITIATOR_NUMBER { get; set; }
        public string INITIATING_BRANCH { get; set; }
        public string INITIATING_BRANCHCODE { get; set; }
        public string INITIATING_DEPT { get; set; }
        public string INITIATING_DEPTCODE { get; set; }
        public Nullable<System.DateTime> INITIATION_DATE { get; set; }
        public string LINE_MANAGER_NUM { get; set; }
        public string LINE_MANAGER_NAME { get; set; }
        public string LINE_MANAGER_APPR { get; set; }
        public Nullable<System.DateTime> LINE_MANAGER_APPR_DATE { get; set; }
        public string BUYER_STATUS { get; set; }
        public string BUYER_COMMENT { get; set; }
        public string PREFERED_VENDOR { get; set; }
        public string PREFERED_VENDOR_ID { get; set; }
        public string ITEM_DESCRIPTION { get; set; }
        public Nullable<System.DateTime> EXPECTED_DELIVERY_DATE { get; set; }
        public string INITIATOR_EMAIL { get; set; }
        public string LINE_MANAGER_EMAIL { get; set; }
        public string ITEM_CATEGORY_ID { get; set; }
        public string PROCUREMENT_BUYER { get; set; }
        public Nullable<decimal> PROCUREMENT_BUYER_ID { get; set; }
        public string LINE_MANAGER_COMMENT { get; set; }
        public Nullable<decimal> MAPTOREQUEST { get; set; }
    }
}
