//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcurementErpVendor
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOURCING_RFQ_ITEM
    {
        public decimal ITEM_NO { get; set; }
        public Nullable<decimal> TEMP_NO { get; set; }
        public string QUANTITY { get; set; }
        public string UNIT_OF_MEAS { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
        public Nullable<decimal> TOTAL_PRICE { get; set; }
        public string RFI_INFO { get; set; }
    }
}
